export const groups = [
   '.Net',
   '2D Artist',
   '3D artist',
   'Accountants',
   'Android',
   'BI',
   'Business Analyst',
   'Business Development',
   'C++',
   'Data Bases',
   'Design',
   'DevOps',
   'English department',
   'HR',
   'IT',
   'iOS',
   'JS',
   'Java',
   'Lawyers',
   'Machine Learning',
   'Managers',
   'Managers Alchevskykh',
   'Marketing Managers',
   'Markup',
   'NodeJS',
   'OM',
   'Operations',
   'PHP',
   'ProMX',
   'Python',
   'QA',
   'Recruiters',
   'Ruby',
   'Sales',
   'Security',
   'Unity 3D',
   'Unreal Engine',
   'Computer Vision',
   'Finance'
  ]
