export const groups = [
   '.Net',
   '2D Artist',
   '3D artist',
   'Android',
   'BI',
   'Business Analyst',
   'Business Development',
   'C++',
   'Data Bases',
   'Design',
   'DevOps',
   'HR',
   'IT',
   'iOS',
   'JS',
   'Java',
   'Machine Learning',
   'Managers',
   'Managers Alchevskykh',
   'Marketing Managers',
   'Markup',
   'NodeJS',
   'Operations',
   'PHP',
   'ProMX',
   'Python',
   'QA',
   'Recruiters',
   'Ruby',
   'Sales',
   'Unity 3D',
   'Unreal Engine',
   'Computer Vision',
   'Finance'
  ]
